### ISSUE TITLE
Auto populate fields v2.5.2 STILL breaks surveys

### ISSUE THREAD

**Issue by thorvardur** [ctsit/auto_populate_fields#48] opened 2020-09-07 13:40 UTC
Hi,

Had the auto-populate module v 2.5.1 enabled in a v 10.0.11 LTS installation of REDCap. Received reports that surveys were freezing.

Isolated it to happening in multi-page surveys on pressing the next page button.

Found a thread on community.project_redcap which pointed here. Saw the ticket was closed here, saying this was fixed in v2.5.2 so I upgraded, the issue remained.

So I upgraded to 2.5.2 - problem remained
Disabled auto populate 2.5.2 - problem solved
Enabled auto populate 2.5.2 - problem again (next button not working on multi-page survey)
Disabled suto populat 2.5.2 - problem solved

This is still a critical error that needs fixing, it may be affecting many sties without them noticing as it only happens when people are completing surveys, so REDCap users do not see any sign of the problem.

Thank you for looking into this,

Thor

**Comment by ChemiKyle** [comment] 2020-09-15 13:52
I'm able to see a javascript error in the console using a survey with multiple pages in REDCap 10.0.11; the "Next Page" button does take me to the next page if I'm using Firefox but using Chrome the button indeed does not work as intended.

@thorvardur are you able to test this on an instance of REDCap 10.0.3 or earlier? No worries if not.

**Comment by pbchase** [comment] 2020-10-09 18:42
addressed by PR #49

**Closed by pbchase** 2020-10-09 18:42 UTC
Labels: bug

**Comment by vkuljak** [comment] 2020-11-04 22:06
I am trying to ise this in survey and no matter what option I select, it does not prepopulate any of the fields. Please advise.
Thanks.
