### ISSUE TITLE
A user reports that the module renders the @READONLY-SURVEY action tag unusable

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/auto_populate_fields#52] opened 2021-01-21 19:16 UTC
https://community.projectredcap.org/questions/99382/auto-populate-fields-and-readonly-survey.html

> Hi. We're using Auto Populate Fields and it is fantastic.
We've encountered a situation where enabling the module seems to render @READONLY-SURVEY action tag unusable. It doesn't seem to matter where the in the project the action tags are called, simply enabling the module alone restricts fields from being grayed-out. We are using Auto Populate Fields - v2.6.0 on REDCap 10.3.7
Any ideas what's going on?
Thanks!

**Comment by mbentz-uf** [comment] 2021-01-22 13:39
I can't reproduce the issue. I tested with the same environment using REDCap 10.3.7 and auto_populate_fields_v2.6.0. After enabling the module, fields marked with __@READONLY-SURVEY__ are disabled on the survey. Maybe their expectation is that it should be disabled on form entry?

**Comment by mbentz-uf** [comment] 2021-01-25 19:29
Attempted to reproduce with [sample project](https://community.projectredcap.org/storage/attachments/18447-democovproj1-2021-01-25-0901redcap.xml) provided by Cameron Coffran.

__Environment__
```
REDCap 10.3.7
auto_populate_fields v2.6.0
```

__Steps taken:__

1. Installed Module with __Enable module on all projects by default__ left unchecked
2. Installed sample project
3. Opened public survey for Sample submission form

__Results__
Fields marked with __@READONLY-SURVEY__ are disabled on the survey.
> ![Survey-readonly fields](https://user-images.githubusercontent.com/75623654/105755518-651aac00-5f19-11eb-9aa6-eba61f409274.png)

**Comment by mbentz-uf** [comment] 2021-02-01 18:37
>Hi Michael,
I tested again and noticed that if I goto External Modules (on project level) -> Configure ->
Enable Auto Populate Fields on survey pages: (check this option)
and go back to my survey the readonly-survey fields are editable.
If I uncheck this option readonly-survey is properly greyed out. So, it seems to be dependent on this checkbox.

In the scenario above, if a field has action tags `"@DEFAULT @READONLY-SURVEY"` the value will be overwritten with `"@DEFAULT"`. Line __52__ causes this. @ChemiKyle Is that the desired behavior of the module or should other action tags be preserved? 
https://github.com/ctsit/auto_populate_fields/blob/71ba4f604ee3ae71a8c9d9a8d610bbdc4335027b/ExternalModule.php#L45-L57

**Comment by mbentz-uf** [comment] 2021-03-05 14:49
Resolved by PR #53

**Closed by mbentz-uf** 2021-03-05 14:49 UTC
